# USB port
port: /dev/imu
# Tf frame id
frame_id: imu_link
# Data reading frequency
frequency: 100
# Sensor operation mode, axis remap config and sign could be found in sensor datasheet
#operation_mode: 0x08 # OPER_MODE_IMU
operation_mode: 0x0C #OPER_MODE_NDOF
axis_remap_config: 0x24
axis_remap_sign: 0x00